{
    "name": "Currency rate provider: BCV",
    "icon": "/poweredbyandy_saas/static/description/icon.png",
    "summary": """Currency rate provider for BCV (Banco Central de Venezuela)""",
    "version": "18.0.1.1.2",
    "category": "Financial Management/Configuration",
    "author": "Anderson Armeya, Odoo Community Association (OCA)",
    "website": "https://github.com/OCA/l10n-venezuela",
    "maintainers": ["andyengit"],
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": ["currency_rate_update"],
    "data": [],
}
